name: Daily Checkin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BASE_URL: ${{ secrets.BASE_URL }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt  # 如果有依赖需要安装，请添加相应的命令

      - name: Run Daily Checkin
        run: |
          python main.py
      

        
